---
- hosts: balancer
  become: yes

  vars:
          firewall_allowed_tcp_ports:
                  - "22"
                  - "80"

          haproxy_backend_servers:
                  - name: 10.19.0.93
                    address: 10.19.0.93:80
                  - name: 10.19.0.94
                    address: 10.19.0.94:80

  roles:
          - geerlingguy.firewall
          - geerlingguy.haproxy

- hosts: app
  become: yes

  vars:
          firewall_allowed_tcp_ports:
                  - "22"
                  - "80"

  roles:
          - geerlingguy.firewall
          - geerlingguy.apache
